#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 16, 2019 07:40:19 PM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

global val, w, root
top = tk.Tk()

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#d9d9d9'  # X11 color: 'gray85'
_ana1color = '#d9d9d9'  # X11 color: 'gray85'
_ana2color = '#ececec'  # Closest X11 color: 'gray92'
font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant" \
        " italic -underline 0 -overstrike 0"

top.geometry("600x446+346+141")
top.title("New Toplevel")
top.configure(background="#d9d9d9")

Label1 = tk.Label(top)
Label1.place(relx=0.283, rely=0.045, height=81, width=254)
Label1.configure(background="#d9d9d9")
Label1.configure(disabledforeground="#a3a3a3")
Label1.configure(foreground="#000000")
_img1 = tk.PhotoImage(file="../EAR/INBOX2.png")
Label1.configure(image=_img1)
Label1.configure(text='''Label''')
Label1.configure(width=254)

Frame1 = tk.Frame(top)
Frame1.place(relx=0.05, rely=0.269, relheight=0.639, relwidth=0.925)

Frame1.configure(relief='groove')
Frame1.configure(borderwidth="2")
Frame1.configure(relief='groove')
Frame1.configure(background="#d9d9d9")
Frame1.configure(width=555)

Label2 = tk.Label(Frame1)
Label2.place(relx=0.036, rely=0.035, height=21, width=154)
Label2.configure(background="#d9d9d9")
Label2.configure(disabledforeground="#a3a3a3")
Label2.configure(font=font9)
Label2.configure(foreground="#000000")
Label2.configure(text='''Sender''')
Label2.configure(width=154)

Label3 = tk.Label(Frame1)
Label3.place(relx=0.423, rely=0.035, height=21, width=194)
Label3.configure(background="#d9d9d9")
Label3.configure(disabledforeground="#a3a3a3")
Label3.configure(font=font9)
Label3.configure(foreground="#000000")
Label3.configure(text='''Subject''')
Label3.configure(width=194)

Label4 = tk.Label(Frame1)
Label4.place(relx=0.072, rely=0.035, height=22, width=32)
Label4.configure(background="#d9d9d9")
Label4.configure(disabledforeground="#a3a3a3")
Label4.configure(foreground="#000000")
_img2 = tk.PhotoImage(file="../EAR/logomail.png")
Label4.configure(image=_img2)
Label4.configure(text='''Label''')
Label4.configure(width=32)

Label5 = tk.Label(Frame1)
Label5.place(relx=0.486, rely=0.018, height=31, width=34)
Label5.configure(background="#d9d9d9")
Label5.configure(disabledforeground="#a3a3a3")
Label5.configure(foreground="#000000")
_img3 = tk.PhotoImage(file="../EAR//rsz_unread.png")
Label5.configure(image=_img3)
Label5.configure(text='''Label''')
Label5.configure(width=34)

TSeparator1 = ttk.Separator(Frame1)
TSeparator1.place(relx=0.009, rely=0.123, relwidth=1.009)

Label6 = tk.Label(Frame1)
Label6.place(relx=0.009, rely=0.158, height=21, width=214)
Label6.configure(background="#d9d9d9")
Label6.configure(disabledforeground="#a3a3a3")
Label6.configure(foreground="#000000")
Label6.configure(text='''adddress email1''')
Label6.configure(width=214)

Label7 = tk.Label(Frame1)
Label7.place(relx=0.414, rely=0.158, height=21, width=264)
Label7.configure(background="#d9d9d9")
Label7.configure(disabledforeground="#a3a3a3")
Label7.configure(foreground="#000000")
Label7.configure(text='''Email subject 1''')
Label7.configure(width=264)

TSeparator2 = ttk.Separator(Frame1)
TSeparator2.place(relx=0.0, rely=0.246, relwidth=1.009)

Button1 = tk.Button(Frame1)
Button1.place(relx=0.901, rely=0.14, height=24, width=47)
Button1.configure(activebackground="#ececec")
Button1.configure(activeforeground="#000000")
Button1.configure(background="#d9d9d9")
Button1.configure(disabledforeground="#a3a3a3")
Button1.configure(foreground="#000000")
Button1.configure(highlightbackground="#d9d9d9")
Button1.configure(highlightcolor="black")
_img4 = tk.PhotoImage(file="../EAR/logo2.png")
Button1.configure(image=_img4)
Button1.configure(pady="0")
Button1.configure(relief='flat')
Button1.configure(text='''Button''')
Button1.configure(width=47)
top.mainloop()
